=== KouhouMohamed/XML/test.dtd
<!ELEMENT A (A|B|C)+>
<!ELEMENT C EMPTY >
<!ELEMENT B EMPTY >
<!ATTLIST A at CDATA "red" >
<!ATTLIST B att (red|black) "black" >
<!ATTLIST C id ID #REQUIRED>
<!ATTLIST B chef IDREF #REQUIRED >
<!ATTLIST A value CDATA #IMPLIED >
<!ATTLIST C mark CDATA #FIXED "IBM" >

=== KouhouMohamed/XML/test.xml
<?xml version="1.0"?>
<!DOCTYPE A SYSTEM "test.dtd">
<A at="green">
    <B chef="Kouhou"/><C id="Kouhou"/><C id="Kouho"/>
    <A value="pardef"><B chef="Kouho"/><C id="mohamed" mark="IBM"/> <B chef="mohamed"/></A>
</A>
